//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersionAttribute("2.1.0.0")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2.1.35.20564")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2.1.35-preview+54501c7512")]
#if NETSTANDARD || NETFRAMEWORK || NETCOREAPP
[System.CodeDom.Compiler.GeneratedCode("Nerdbank.GitVersioning.Tasks","3.0.28.11123")]
#endif
internal static partial class ThisAssembly {
    internal const string AssemblyVersion = "2.1.0.0";
    internal const string AssemblyFileVersion = "2.1.35.20564";
    internal const string AssemblyInformationalVersion = "2.1.35-preview+54501c7512";
    internal const string AssemblyName = "Unity.VersionControl.Git.UI";
    internal const string AssemblyTitle = "Unity.VersionControl.Git.UI";
    internal const string AssemblyConfiguration = "Debug";
    internal const string GitCommitId = "54501c751251532c37eff57ba0f42773695387c2";
    internal static readonly System.DateTime GitCommitDate = new System.DateTime(637541857770000000L, System.DateTimeKind.Utc);
    internal const string RootNamespace = "UI";
}
